image: bwengals/bayes-workshop:latest
ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
- init: /workspace/testgitpod/run.sh
  command: cp -r /workspace/testgitpod/.jupyter /home/gitpod/
